package com.aptron.intent;
import androidx.appcompat.app.AppCompatActivity;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;

public class MainActivity extends AppCompatActivity implements View.OnClickListener {
    Button b1,b2,b3,b4,b5,b6,b7,b8;
    EditText et;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        b1= findViewById(R.id.b1);
        b2= findViewById(R.id.b2);
        b3= findViewById(R.id.b3);
        b4= findViewById(R.id.b4);
        b5= findViewById(R.id.b5);
        b6= findViewById(R.id.b6);
        b7= findViewById(R.id.b7);
        b8= findViewById(R.id.b8);
        et= findViewById(R.id.edtxt);

        b1.setOnClickListener(this);
        b2.setOnClickListener(this);
        b3.setOnClickListener(this);
        b4.setOnClickListener(this);
        b5.setOnClickListener(this);
        b6.setOnClickListener(this);
        b7.setOnClickListener(this);
        b8.setOnClickListener(this);
        et.setOnClickListener(this);

    }

    @Override
    public void onClick(View view) {
        Intent intent, chooser;
        switch (view.getId())
        {
            case R.id.b1:
                intent =new Intent(Intent.ACTION_VIEW);
                intent.setData(Uri.parse("geo:@28.470807,77.0447379"));
                chooser = Intent.createChooser(intent,"Open Map");
                startActivity(chooser);
                break;
            case R.id.b2:
                intent = new Intent(Intent.ACTION_SEND);
                String[] mail ={"yamini99.ys@gmail.com","syamini502@gmail.com"};
                intent.putExtra(Intent.EXTRA_EMAIL,mail);
                intent.putExtra(Intent.EXTRA_TITLE,"FeedBack Mail");
                intent.putExtra(Intent.EXTRA_TEXT,"This is an Autogenerated Mail");

                intent.setType("text/plain");
                chooser = Intent.createChooser(intent,"Send FeedBack");
                startActivity(chooser);
                break;
            case R.id.b3:
                intent = new Intent(Intent.ACTION_VIEW);
                intent.setData(Uri.parse("http://aptrongurgaon.in/"));
                chooser = Intent.createChooser(intent,"Open WebSite");
                startActivity(chooser);
                break;
            case R.id.b4:
                intent= new Intent(Intent.ACTION_SEND);
                intent.putExtra(Intent.EXTRA_TEXT, "Hey! I'm Yamini.");
                intent.setPackage("com.whatsapp"); //if not specified then it will open up messaging app
                intent.setType("text/plain");
                startActivity(intent);
                break;
            case R.id.b5:
                intent = new Intent(Intent.ACTION_VIEW);
                intent.setData(Uri.parse("http://www.facebook.com/"));
                chooser = Intent.createChooser(intent,"Open WebSite");
                startActivity(chooser);
                break;
            case R.id.b6:
                intent = new Intent(Intent.ACTION_VIEW);
                intent.setData(Uri.parse("market://details?id=com.Approprice.Approprice&hl=en_IN"));
                chooser= Intent.createChooser(intent,"Download My App");
                startActivity(chooser);
                break;
            case R.id.b7:
                intent  = new Intent(MainActivity.this,Main2Activity.class);
                intent.putExtra("name",et.getText().toString());
                startActivity(intent);
                break;
            case R.id.b8:
                intent =new Intent(Intent.ACTION_DIAL);
                intent.setData(Uri.parse("tel:+919760852898"));
                startActivity(intent);
                break;
        }
    }
}